In [1]:
import pandas as pd

In [3]:
df=pd.read_csv('movie.csv')

In [4]:
df.head()

,title,year,color,content_rating,duration,director_name,director_fb,actor1,actor1_fb,actor2,...,actor3_fb,gross,genres,num_reviews,num_voted_users,plot_keywords,language,country,budget,imdb_score
0,Avatar,2009.0,Color,PG-13,178.0,James Cameron,0.0,CCH Pounder,1000.0,Joel David Moore,...,855.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,723.0,886204,avatar|future|marine|native|paraplegic,English,USA,237000000.0,7.9
1,Pirates of the Caribbean: At World's End,2007.0,Color,PG-13,169.0,Gore Verbinski,563.0,Johnny Depp,40000.0,Orlando Bloom,...,1000.0,309404152.0,Action|Adventure|Fantasy,302.0,471220,goddess|marriage ceremony|marriage proposal|pi...,English,USA,300000000.0,7.1
2,Spectre,2015.0,Color,PG-13,148.0,Sam Mendes,0.0,Christoph Waltz,11000.0,Rory Kinnear,...,161.0,200074175.0,Action|Adventure|Thriller,602.0,275868,bomb|espionage|sequel|spy|terrorist,English,UK,245000000.0,6.8
3,The Dark Knight Rises,2012.0,Color,PG-13,164.0,Christopher Nolan,22000.0,Tom Hardy,27000.0,Christian Bale,...,23000.0,448130642.0,Action|Thriller,813.0,1144337,deception|imprisonment|lawlessness|police offi...,English,USA,250000000.0,8.5
4,Star Wars: Episode VII - The Force Awakens,NaN,NaN,NaN,NaN,Doug Walker,131.0,Doug Walker,131.0,Rob Walker,...,NaN,NaN,Documentary,NaN,8,NaN,NaN,NaN,NaN,7.1

In [8]:
df.shape

(4916, 22)

In [ ]:
## 16- how many movies are in hindi? how many hindi movies are there after the year 2000?

In [13]:
df.loc[df['language']=='Hindi'].shape[0]

28

In [14]:
df.loc[(df['language']=='Hindi') & (df['year']>2000)].shape[0]

25

In [20]:
## 17- group the movies by language and find out the avg budget of the country egypt

In [110]:
d1=df.groupby(['language','country']).head()
d1

,title,year,color,content_rating,duration,director_name,director_fb,actor1,actor1_fb,actor2,...,actor3_fb,gross,genres,num_reviews,num_voted_users,plot_keywords,language,country,budget,imdb_score
0,Avatar,2009.0,Color,PG-13,178.0,James Cameron,0.0,CCH Pounder,1000.0,Joel David Moore,...,855.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,723.0,886204,avatar|future|marine|native|paraplegic,English,USA,237000000.0,7.9
1,Pirates of the Caribbean: At World's End,2007.0,Color,PG-13,169.0,Gore Verbinski,563.0,Johnny Depp,40000.0,Orlando Bloom,...,1000.0,309404152.0,Action|Adventure|Fantasy,302.0,471220,goddess|marriage ceremony|marriage proposal|pi...,English,USA,300000000.0,7.1
2,Spectre,2015.0,Color,PG-13,148.0,Sam Mendes,0.0,Christoph Waltz,11000.0,Rory Kinnear,...,161.0,200074175.0,Action|Adventure|Thriller,602.0,275868,bomb|espionage|sequel|spy|terrorist,English,UK,245000000.0,6.8
3,The Dark Knight Rises,2012.0,Color,PG-13,164.0,Christopher Nolan,22000.0,Tom Hardy,27000.0,Christian Bale,...,23000.0,448130642.0,Action|Thriller,813.0,1144337,deception|imprisonment|lawlessness|police offi...,English,USA,250000000.0,8.5
5,John Carter,2012.0,Color,PG-13,132.0,Andrew Stanton,475.0,Daryl Sabara,640.0,Samantha Morton,...,530.0,73058679.0,Action|Adventure|Sci-Fi,462.0,212204,alien|american civil war|male nipple|mars|prin...,English,USA,263700000.0,6.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4805,The World Is Mine,2015.0,Color,NaN,104.0,Nicolae Constantin Tanase,0.0,Iulia Ciochina,0.0,Ana Maria Guran,...,0.0,NaN,Drama,5.0,354,NaN,Romanian,Romania,168000.0,6.5
4822,The Brain That Sings,2013.0,Color,NaN,62.0,Amal Al-Agroobi,58.0,NaN,NaN,NaN,...,NaN,NaN,Documentary|Family,NaN,18,autism|middle east|music therapy|united arab e...,Arabic,United Arab Emirates,125000.0,8.2
4895,Stories of Our Lives,2014.0,Black and White,NaN,60.0,Jim Chuchu,0.0,Paul Ogola,147.0,Olwenya Maina,...,4.0,NaN,Drama,6.0,70,NaN,Swahili,Kenya,15000.0,7.4
4900,The Circle,2000.0,Color,Not Rated,90.0,Jafar Panahi,397.0,Fereshteh Sadre Orafaiy,5.0,Nargess Mamizadeh,...,0.0,673780.0,Drama,64.0,4555,abortion|bus|hospital|prison|prostitution,Persian,Iran,10000.0,7.5
4907,Cavite,2005.0,Color,Not Rated,80.0,Neill Dela Llana,0.0,Ian Gamazon,0.0,Edgar Tancangco,...,0.0,70071.0,Thriller,35.0,589,jihad|mindanao|philippines|security guard|squa...,English,Philippines,7000.0,6.3

In [112]:
d1.loc[d1['country']=='Egypt','budget'].mean()

1500000.0

In [26]:
## 18- how many movies are from 1970s and imbd scores greator than 8?

In [114]:
df.loc[(df['year'].between(1970,1979,inclusive=True)) & (df['imdb_score']>8)].shape[0]

/var/folders/bf/76rc9pvx4y95pxbrlkk63m5m0000gn/T/ipykernel_18918/3464721929.py:1: FutureWarning: Boolean inputs to the `inclusive` argument are deprecated in favour of `both` or `neither`.
  df.loc[(df['year'].between(1970,1979,inclusive=True)) & (df['imdb_score']>8)].shape[0]

19

In [ ]:
##  19 was not there in the options so i have chosen 2 in the quiz

In [41]:
## 19- how many movies rated R,PG13 or PG?

In [43]:
df.loc[(df['content_rating']=='R')+(df['content_rating']=='PG-13')+(df['content_rating']=='PG')].shape[0]

4164

In [44]:
## 20- find out movies where actor1 is johhny depp and find out how many movies of his were directed by gore verbinski

In [48]:
df.loc[df['actor1']=='Johnny Depp'].shape[0]

36

In [47]:
df.loc[(df['actor1']=='Johnny Depp') & (df['director_name']=='Gore Verbinski')].shape[0]

5

In [49]:
## 21- display the movies with imbd score with highest to lowest to find the avg imbd score

In [113]:
d1=df.sort_values(by='imdb_score',ascending=False)
d1

,title,year,color,content_rating,duration,director_name,director_fb,actor1,actor1_fb,actor2,...,actor3_fb,gross,genres,num_reviews,num_voted_users,plot_keywords,language,country,budget,imdb_score
2725,Towering Inferno,NaN,Color,NaN,65.0,John Blanchard,0.0,Martin Short,770.0,Andrea Martin,...,176.0,NaN,Comedy,NaN,10,NaN,English,Canada,NaN,9.5
1920,The Shawshank Redemption,1994.0,Color,R,142.0,Frank Darabont,0.0,Morgan Freeman,11000.0,Jeffrey DeMunn,...,461.0,28341469.0,Crime|Drama,199.0,1689764,escape from prison|first person narration|pris...,English,USA,25000000.0,9.3
3402,The Godfather,1972.0,Color,R,175.0,Francis Ford Coppola,0.0,Al Pacino,14000.0,Marlon Brando,...,3000.0,134821952.0,Crime|Drama,208.0,1155770,crime family|mafia|organized crime|patriarch|r...,English,USA,6000000.0,9.2
2779,Dekalog,NaN,Color,TV-MA,55.0,NaN,NaN,Krystyna Janda,20.0,Olaf Lubaszenko,...,2.0,447093.0,Drama,53.0,12590,meaning of life|moral challenge|morality|searc...,Polish,Poland,NaN,9.1
4312,Kickboxer: Vengeance,2016.0,NaN,NaN,90.0,John Stockwell,134.0,Matthew Ziff,260000.0,T.J. Storm,...,354.0,NaN,Action,2.0,246,NaN,NaN,USA,17000000.0,9.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2266,Superbabies: Baby Geniuses 2,2004.0,Color,PG,88.0,Bob Clark,84.0,Scott Baio,650.0,Vanessa Angel,...,177.0,9109322.0,Comedy|Family|Sci-Fi,32.0,25371,computer|good versus evil|mind control|science...,English,Germany,20000000.0,1.9
2240,Disaster Movie,2008.0,Color,PG-13,88.0,Jason Friedberg,82.0,Carmen Electra,869.0,Tony Cox,...,329.0,14174654.0,Comedy,111.0,74945,disaster|glass|mousetrap|natural disaster|scat...,English,USA,25000000.0,1.9
4498,The Helix... Loaded,2005.0,Color,R,97.0,A. Raven Cruz,0.0,Scott Levy,639.0,Vanilla Ice,...,94.0,NaN,Action|Adventure|Comedy|Fantasy|Sci-Fi,3.0,534,cnn reporter|ellipsis in title|matrix|punctuat...,English,USA,1000000.0,1.9
1126,Foodfight!,2012.0,Color,PG,91.0,Lawrence Kasanoff,11.0,Jerry Stiller,719.0,Larry Miller,...,500.0,NaN,Action|Animation|Comedy|Family|Fantasy,12.0,4377,femme fatale|food|pun|supermarket|troubled pro...,English,USA,65000000.0,1.7
2789,Justin Bieber: Never Say Never,2011.0,Color,G,115.0,Jon M. Chu,209.0,Usher Raymond,569.0,Sean Kingston,...,41.0,73000942.0,Documentary|Music,84.0,74351,boyhood friend|manager|plasma tv|prodigy|star,English,USA,13000000.0,1.6

In [56]:
d1.agg({'imdb_score':'mean'})

imdb_score    6.437429
dtype: float64

In [57]:
## 22- how many movies with atleast one of the 3 actors with more than 10,000 fb likes

In [60]:
df.loc[(df['actor1_fb']>10000)+(df['actor2_fb']>10000)+(df['actor3_fb']>10000)].shape[0]

1337

In [61]:
## 23- how many columns contain missing values?

In [62]:
df.isnull().sum()

title                0
year               106
color               19
content_rating     300
duration            15
director_name      102
director_fb        102
actor1               7
actor1_fb            7
actor2              13
actor2_fb           13
actor3              23
actor3_fb           23
gross              862
genres               0
num_reviews         49
num_voted_users      0
plot_keywords      152
language            12
country              5
budget             484
imdb_score           0
dtype: int64

In [64]:
## 24- select movies that are either rated PG13 or were made after 2010. Find out title of highest gross movie among them

In [68]:
df.loc[(df['content_rating']=='PG-13')+(df['year']>2010)].sort_values('gross',ascending=False).head(1)

,title,year,color,content_rating,duration,director_name,director_fb,actor1,actor1_fb,actor2,...,actor3_fb,gross,genres,num_reviews,num_voted_users,plot_keywords,language,country,budget,imdb_score
0,Avatar,2009.0,Color,PG-13,178.0,James Cameron,0.0,CCH Pounder,1000.0,Joel David Moore,...,855.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,723.0,886204,avatar|future|marine|native|paraplegic,English,USA,237000000.0,7.9

In [70]:
## 25- how many movies are directed by steven spielberg? find out the highest budget of the movie directed by him

In [72]:
df.loc[(df['director_name']=='Steven Spielberg')].shape[0]

26

In [91]:
df.loc[(df['director_name']=='Steven Spielberg')].sort_values('budget',ascending=False).head(1)

,title,year,color,content_rating,duration,director_name,director_fb,actor1,actor1_fb,actor2,...,actor3_fb,gross,genres,num_reviews,num_voted_users,plot_keywords,language,country,budget,imdb_score
54,Indiana Jones and the Kingdom of the Crystal S...,2008.0,Color,PG-13,122.0,Steven Spielberg,14000.0,Harrison Ford,11000.0,Ray Winstone,...,1000.0,317011114.0,Action|Adventure|Fantasy,470.0,333847,cult figure|femme fatale|indiana jones|unsubti...,English,USA,185000000.0,6.2